spring:
  application:
    name: security

  profiles:
    default: local
    active: local

  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(fLE1DKIKnY0M6SS0QTawTRIuiaN2GgJcPLA957EW2gkthhq5R43NDmRCj6UbbOv3)
    username: ENC(aDn3Ap1UO1nVF5s4haHo2w==)
    password: ENC(BAmRa3DG0KaGzFf+JyK5nA==)

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j

server:
  port: 9999

url: http://localhost:4200

jasypt:
  encryptor:
    password: ${password}

#logging:
#  level:
#    org:
#      springframework.security.web.FilterChainProxy: DEBUG