CREATE TABLE USERS
(
    ID       INT         NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL UNIQUE ,
    PASSWORD VARCHAR(45) NOT NULL,
    ENABLED  INT     NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHORITIES
(
    ID        INT         NOT NULL AUTO_INCREMENT,
    USERNAME  VARCHAR(45) NOT NULL UNIQUE ,
    AUTHORITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);


INSERT IGNORE INTO USERS VALUES (NULL, 'happy', '12345', '1');
INSERT IGNORE INTO AUTHORITIES VALUES (NULL, 'happy', 'write');


CREATE TABLE customer
(
    ID    INT         NOT NULL AUTO_INCREMENT,
    email VARCHAR(45) NOT NULL UNIQUE,
    PWD   VARCHAR(45) NOT NULL,
    ROLE  VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO customer(EMAIL, PWD, ROLE) VALUES ('test@test.com', '12345', 'admin');